executor: "KubernetesExecutor"

# Images
images:
  airflow:
    repository: my-dags
    tag: ~
    # Specifying digest takes precedence over tag.
    digest: ~
    pullPolicy: IfNotPresent

postgresql:
  enabled: true
  auth:
    username: airflow
    password: airflow
    database: airflow

  primary:
    persistence:
      enabled: false

  image:
    tag: latest

dags:
  gitSync:
    enabled: true

    # git repo clone url
    # ssh example: git@github.com:apache/airflow.git
    # https example: https://github.com/apache/airflow.git
    repo: https://github.com/temi109/Kubernetes-Airflow.git
    branch: main
    rev: HEAD
    # Git branch you're currently using
    ref: main
    depth: 1
    # the number of consecutive failures allowed before aborting
    maxFailures: 0
    subPath: "dags"
    credentialsSecret: git-credentials


logs:
  persistence:
    # Enable persistent volume for storing logs
    enabled: True
    # If using a custom storageClass, pass name here
    storageClassName: manual
    ## the name of an existing PVC to use
    existingClaim: airflow-logs-pvc


serviceAccount:
  create: false
  name: airflow-sa
